### ISSUE TITLE
TOS

### ISSUE THREAD

**Issue by endomorphosis** [Agora-X/DALLE3-API#11]
is this against the TOS, and will they ban accounts for this? You should let people know ahead of time, that this is not an "unofficial api", this is literally a webscraper.

from: https://www.microsoft.com/en-us/servicesagreement
"ii. Extracting Data. Unless explicitly permitted, you may not use web scraping, web harvesting, or web data extraction methods to extract data from the AI services."

**Comment by kyegomez** [comment]
@endomorphosis stop being police and contribute to open source, you'll be much happier.
