### ISSUE TITLE
I always get this error: "TypeError: Binary Location Must be a String"

### ISSUE THREAD

**Issue by kukucsi** [Agora-X/DALLE3-API#30]
I have written this code after the example in this repo:

```
cookie = "i pasted here the _U cookie"
dalle = Dalle(cookie)
dalle.create("apple")
urls = dalle.get_urls()
dalle.download(urls, "images/")
```

When I run this code, I get the following error:

TypeError: Binary Location Must be a String

The problem is with the `dalle = Dalle(cookie)` line.

The fix for this is probably easy, but I just can't figure it out.

**Comment by Be1Happy** [comment]
Have the same problem,still unsolved.
