### ISSUE TITLE
ImportError: cannot import name 'Dalle' from partially initialized module 'dalle3'

### ISSUE THREAD

**Issue by syntaxsurge** [Agora-X/DALLE3-API#6]
**Describe the bug**
    from dalle3 import Dalle
ImportError: cannot import name 'Dalle' from partially initialized module 'dalle3' (most likely due to a circular import)

**Comment by kyegomez** [comment]
@syntaxsurge Excuse me try this:

`python3.11 -m pip3 install --upgrade dalle3`
